jenkins:
  systemMessage: Welcome to the Chocolatine-Powered Marvin Jenkins Instance.

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "chocolateen"
          name: "Hugo"
          password: "${USER_CHOCOLATEEN_PASSWORD}"
        - id: "vaugie_g"
          name: "Garance"
          password: "${USER_VAUGIE_G_PASSWORD}"
        - id: "i_dont_know"
          name: "Jeremy"
          password: "${USER_I_DONT_KNOW_PASSWORD}"
        - id: "nasso"
          name: "Nassim"
          password: "${USER_NASSO_PASSWORD}"

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            permissions:
              - "Overall/Administer"
            entries:
              - user: "chocolateen"
          - name: "ape"
            description: "Pedagogical team member"
            permissions:
              - "Job/Build"
              - "Workspace/Read"
            entries:
              - user: "i_dont_know"
          - name: "gorilla"
            description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
            permissions:
              - "Job/Create"
              - "Job/Move"
              - "Job/Configure"
              - "Job/Delete"
              - "Job/Cancel"
              - "Job/Build"
              - "Workspace/Read"
              - "Overall/Read"
            entries:
              - user: "vaugie_g"
          - name: "assist"
            description: "Assistant"
            permissions:
              - "Overall/Read"
            entries:
              - user: "nasso"

jobs:
  - file: /var/jenkins_home/job_dsl.groovy

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false